[tool.poetry]
name = "analyse-survie"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
numpy = "^1.26.0"
matplotlib = "^3.8.0"
pandas = "^2.1.1"
jupyter = "^1.0.0"
statsmodels = "^0.14.0"
scikit-learn = "^1.3.1"
seaborn = "^0.13.0"
lifelines = "^0.27.8"

[tool.poetry.group.dev.dependencies]
black = {extras = ["jupyter"], version = "^23.10.0"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
